tap "homebrew/bundle"
tap "homebrew/cask-versions"
tap "homebrew/cask-fonts"

brew "autojump"
brew "qemu"
brew "lima"
brew "colima"
brew "coreutils"
brew "docker"
brew "docker-buildx"
brew "docker-compose"
brew "docker-credential-helper"
brew "gh"
brew "git"
brew "git-delta"
brew "ripgrep"
brew "jq"
brew "ktlint"
brew "tldr"
brew "tree"
brew "zsh-autosuggestions"
brew "autojump"
brew "neovim"
brew "lazygit"
brew "php" # For alfred-github-workflow

cask "1password"
cask "1password-cli"
cask "alfred"
cask "alt-tab"
cask "anybar"
cask "browserosaurus"
cask "discord"
cask "rectangle"
cask "signal"
cask "spotify"
cask "swiftbar"
cask "the-unarchiver"
cask "visual-studio-code"
cask "vlc"
cask "zoom"
cask "kitty"
cask "qbittorrent"

# Jobb
# Also need sdkman, which is not in brew.sh at the time of writing
tap "gdubw/gng"
brew "nvm"
brew "direnv"
brew "gng"
brew "pyenv"
cask "intellij-idea"
cask "google-chrome"
cask "google-cloud-sdk"
# cask "slack" # Utkommentert pga gjentakande install

#brew "gradle"
#brew "pngcrush"

#cask "insomnia"
#brew "switchaudio-osx"
#brew "chezmoi"

# tap "adoptopenjdk/openjdk"
# tap "buildpacks/tap"
# tap "dbt-labs/dbt"
# tap "dbt-labs/dbt"
# tap "gdubw/gng"
# brew "python@3.10"
# brew "python@3.9"
# brew "ciphey"
# brew "deno"
# brew "ffmpeg"
# brew "imagemagick"
# brew "openjdk"
# brew "neovim"
# brew "nmap"
# brew "rustup-init"
# brew "terraformer"
# brew "tfenv"
# brew "tgenv"
# brew "buildpacks/tap/pack"
# brew "dbt-labs/dbt/dbt-bigquery"
# brew "gdubw/gng/gng"
# cask "adoptopenjdk11"
# cask "adoptopenjdk8"
# cask "android-platform-tools"
# cask "appcleaner"
# cask "background-music"
# cask "calibre"
# cask "dotnet-sdk"
# cask "gimp"
# cask "inkscape"
# cask "kdiff3"
# cask "minecraft"
# cask "miniconda"
# cask "obsidian"
# cask "openscad"
# cask "plex"
# cask "plex-media-server"
# cask "qbittorrent"
# cask "sonic-pi"
# cask "sqlcl"
# cask "steam"
# cask "talon"
